version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/reactecommerce
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reactecommerce
    ports:
      - "5432:5432"
