BEGIN;

-- 1️⃣ Agregar columna discount_percentage (seguro)
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS discount_percentage numeric(5,2) DEFAULT 0;

-- 2️⃣ Crear tabla product_reviews
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer REFERENCES public.products(id),
    user_id integer REFERENCES public.users(id),
    rating integer CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- 3️⃣ Crear tabla product_views
CREATE TABLE IF NOT EXISTS public.product_views (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer REFERENCES public.products(id),
    user_id integer REFERENCES public.users(id),
    viewed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

COMMIT;

